//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.04 at 04:08:16 PM BRT 
//


package com.fico.ps.lac.blaze.generic.bom.domain;

public enum AuditStepScope {

    BUSINESS,
    TECHNICAL;

}
