//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.04 at 04:08:16 PM BRT 
//


package com.fico.ps.lac.blaze.generic.bom.output;

import java.io.Serializable;

import com.fico.ps.lac.blaze.generic.bom.domain.AuditStepScope;



public class AuditStep implements Serializable{

	private static final long serialVersionUID = 1L;
	
    protected String stepName;
    protected AuditStepScope scope;
    protected String stepMessage;
    protected Integer stepNumber;

	public AuditStep() {
		super();
	}

	public String getStepName() {
		return stepName;
	}

	public void setStepName(String stepName) {
		this.stepName = stepName;
	}

	public AuditStepScope getScope() {
		return scope;
	}



	public void setScope(AuditStepScope scope) {
		this.scope = scope;
	}



	public String getStepMessage() {
		return stepMessage;
	}



	public void setStepMessage(String stepMessage) {
		this.stepMessage = stepMessage;
	}



	public Integer getStepNumber() {
		return stepNumber;
	}



	public void setStepNumber(Integer stepNumber) {
		this.stepNumber = stepNumber;
	}



}
