@echo off

set ADVISOR_SERVER_HOME=C:\Blaze\Advisor75
set ADVISOR_COMMON_HOME=C:\Blaze\Advisor75
set ADVISOR_ENGINE_HOME=C:\Blaze\Advisor75
set ADVISOR_IRT_HOME=C:\Blaze\Advisor75
set ADVISOR_LICENSE=%ADVISOR_SERVER_HOME%\..\license

set ADVSVR_CLASSPATH=%ADVISOR_LICENSE%
set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_COMMON_HOME%\lib\AdvCommon.jar
set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_ENGINE_HOME%\lib\Advisor.jar
set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\AdvisorSvr.jar
set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_IRT_HOME%\lib\InnovatorRT.jar
set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_IRT_HOME%\lib\dmcom.jar

set CLASSPATH=build\classes;%ADVSVR_CLASSPATH%

set CLASSPATH=%CLASSPATH%;C:\FICO\GIT\Blaze\Projetos\Spurs\javaProjects\Spurs\target\Spurs-1.0.jar

set PATH=%JAVA_HOME%\bin;%PATH%
