@REM 
@REM Generated by the Advisor Quick Deployer 
@REM

@rem This material is the confidential, unpublished property of 
@rem Fair Isaac Corporation. Receipt or possession of this material does not 
@rem convey rights to divulge, reproduce, use, or allow others to use it 
@rem without the specific written authorization of Fair Isaac Corporation and 
@rem use must conform strictly to the license agreement.
@rem
@rem Copyright (c) 2013-2018 Fair Isaac Corporation. All Rights Reserved.
@REM 
@REM
@REM 
@REM 
@REM Generated by the Advisor Quick Deployer 
@REM

@rem This material is the confidential, unpublished property of 
@rem Fair Isaac Corporation. Receipt or possession of this material does not 
@rem convey rights to divulge, reproduce, use, or allow others to use it 
@rem without the specific written authorization of Fair Isaac Corporation and 
@rem use must conform strictly to the license agreement.
@rem
@rem Copyright (c) 2013-2018 Fair Isaac Corporation. All Rights Reserved.
@REM 
@REM
@REM 
@REM
@REM set Tomcat home
@REM
@set TOMCAT_HOME=C:\apache-tomcat-8.5.24
@set DEPLOY_DIR=%TOMCAT_HOME%\webapps


@REM
@REM set Java JDK home
@REM
@set JAVA_HOME=C:\Java\jdk


@REM
@REM Set Advisor Home variables
@REM
@set ADVISOR_SERVER_HOME=C:\Blaze\Advisor75
@set ADVISOR_COMMON_HOME=C:\Blaze\Advisor75
@set ADVISOR_ENGINE_HOME=C:\Blaze\Advisor75
@set ADVISOR_IRT_HOME=C:\Blaze\Advisor75
@set ADVISOR_LICENSE=%ADVISOR_SERVER_HOME%\..\license

@REM
@REM Set the Advisor classes
@REM
@set ADVSVR_CLASSPATH=%ADVISOR_LICENSE%
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_COMMON_HOME%\lib\AdvCommon.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_ENGINE_HOME%\lib\Advisor.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\AdvisorSvr.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_IRT_HOME%\lib\InnovatorRT.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_IRT_HOME%\lib\dmcom.jar



@REM
@REM JavaEE jars
@REM
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\FastInfoset.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\gmbal-api-only.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\ha-api.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\javax.annotation-api.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\javax.xml.soap-api.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxb-api.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxb-core.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxb-impl.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxb-jxc.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxb-xjc.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxws-api.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxws-rt.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxws-tools.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jsr181-api.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\management-api.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\mimepull.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\policy.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\resolver.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\saaj-impl.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\stax-ex.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\stax2-api.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\streambuffer.jar
@set ADVSVR_CLASSPATH=%ADVSVR_CLASSPATH%;%ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\woodstox-core-asl.jar
@REM
@REM Now create a new classpath setting
@REM
@set CLASSPATH=build\classes;%ADVSVR_CLASSPATH%

@REM
@REM Add, if any, rulebase support class/interface, e.g. object model, jar file(s)
@REM
@REM set CLASSPATH=%CLASSPATH%;C:\model\support.jar;

@REM
@REM Now set up PATH
@REM
@set PATH=%JAVA_HOME%\bin;%PATH%

:end
