@REM
@REM Generated by the Advisor Quick Deployer 
@REM

@rem This material is the confidential, unpublished property of 
@rem Fair Isaac Corporation. Receipt or possession of this material does not 
@rem convey rights to divulge, reproduce, use, or allow others to use it 
@rem without the specific written authorization of Fair Isaac Corporation and 
@rem use must conform strictly to the license agreement.
@rem
@rem Copyright (c) 2013-2018 Fair Isaac Corporation. All Rights Reserved.
@REM 
@REM


@REM 
@REM set package 
@REM
@set package=\qdspurs

@REM 
@REM setup:
@REM       WEB-INF/classes
@REM
@mkdir build\tmp\WEB-INF\classes%package%
@copy build\classes%package%\*.class build\tmp\WEB-INF\classes%package%
@copy Spurs.server build\tmp\WEB-INF\classes%package%\ndconfig.server
@REM 
@REM setup:
@REM       WEB-INF/web.xml
@REM
@copy web.xml build\tmp\WEB-INF
@copy sun-jaxws.xml build\tmp\WEB-INF

@REM 
@REM setup:
@REM       WEB-INF/lib
@REM
@mkdir build\tmp\WEB-INF\lib


@REM Add mandatory Advisor jar files
@copy %ADVISOR_COMMON_HOME%\lib\AdvCommon.jar build\tmp\WEB-INF\lib\AdvCommon.jar
@copy %ADVISOR_ENGINE_HOME%\lib\Advisor.jar build\tmp\WEB-INF\lib\Advisor.jar
@copy %ADVISOR_SERVER_HOME%\lib\AdvisorSvr.jar build\tmp\WEB-INF\lib\AdvisorSvr.jar
@copy %ADVISOR_COMMON_HOME%\lib\ecj.jar build\tmp\WEB-INF\lib\ecj.jar
@copy %ADVISOR_COMMON_HOME%\lib\json.jar build\tmp\WEB-INF\lib\json.jar
@copy %ADVISOR_COMMON_HOME%\lib\bouncycastle-extracted.jar build\tmp\WEB-INF\lib\bouncycastle-extracted.jar
@copy %ADVISOR_IRT_HOME%\lib\dmcom.jar build\tmp\WEB-INF\lib\dmcom.jar

@copy %ADVISOR_COMMON_HOME%\lib\jaxen-1.1.4.jar build\tmp\WEB-INF\lib\jaxen-1.1.4.jar
@REM 
@REM If you use binary format Advisor project file,
@REM InnovatorRT.jar is not necessary.
@copy %ADVISOR_IRT_HOME%\lib\InnovatorRT.jar build\tmp\WEB-INF\lib\InnovatorRT.jar

@REM
@REM Depending on the rulebase you use, you may need to put more Advisor related
@REM jar files into this EAR file. For further details on the Advisor jar files
@REM required, check the Advisor documentation. If you add more jar files, you will need to 
@REM include them in ManifestEjb.mf if there is one.
@REM

@REM Add, if any, rulebase support class/interface, e.g. object model, jar file(s)
@REM If you add support jar files here, modify ManifestEjb.mf or the 
@REM Manifest file for the client application depending upon the script to be run 
@REM is for server application or client application respectively, if there is a 
@REM Manifest file,as per the documentation. Also run Server.bat or 
@REM client app script again before running this.
@REM copy C:\model\support.jar build\tmp\WEB-INF\lib\support.jar
@REM
@mkdir license\com\blazesoft\licenseKeys
@copy %ADVISOR_LICENSE%\com\blazesoft\licenseKeys\keys.properties license\com\blazesoft\licenseKeys\keys.properties
@cd license
@"%JAVA_HOME%\bin\jar.exe" cvf ..\build\tmp\WEB-INF\lib\license.jar .
@cd ..
@rmdir license /s/q


@REM 
@REM add JAX-WS RI jars:
@REM       WEB-INF/lib
@REM
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\FastInfoset.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\gmbal-api-only.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\ha-api.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\javax.annotation-api.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\javax.xml.soap-api.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxb-api.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxb-core.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxb-impl.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxb-jxc.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxb-xjc.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxws-api.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxws-rt.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jaxws-tools.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\jsr181-api.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\management-api.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\mimepull.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\policy.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\resolver.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\saaj-impl.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\stax-ex.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\stax2-api.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\streambuffer.jar build\tmp\WEB-INF\lib
@copy %ADVISOR_SERVER_HOME%\lib\glassfish\jaxws-ri\woodstox-core-asl.jar build\tmp\WEB-INF\lib

@cd build\tmp
@"%JAVA_HOME%\bin\jar.exe" Mcf ..\SpursServer.war .

@cd ..\..
@rmdir build\tmp /s/q
:end
