@REM 
@REM Generated by the Advisor Quick Deployer 
@REM

@rem This material is the confidential, unpublished property of 
@rem Fair Isaac Corporation. Receipt or possession of this material does not 
@rem convey rights to divulge, reproduce, use, or allow others to use it 
@rem without the specific written authorization of Fair Isaac Corporation and 
@rem use must conform strictly to the license agreement.
@rem
@rem Copyright (c) 2013-2018 Fair Isaac Corporation. All Rights Reserved.
@REM 
@REM
@REM 

@REM 
@REM set up build directory
@REM 
@if EXIST "build\classes" goto setJavaHome
@mkdir build\classes

:setJavaHome
@REM
@REM set Java JDK home
@REM
@set JAVA_HOME=C:\Java\jdk

@REM
@REM set up classpath
@REM
@set CLASSPATH=build\classes;%CLASSPATH%

@REM
@REM Now set up PATH
@REM
@set PATH=%JAVA_HOME%\bin;%PATH%

:end
